name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Substitua por sua branch de produção, se for diferente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build
      run: |
        npm install
        npm run build  # ou o comando que você usa para gerar o build no ./dist

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages  # A branch para onde os arquivos serão enviados
        folder: dist      # O diretório que você deseja publicar no GitHub Pages
        token: ${{ secrets.GITHUB_TOKEN }}  # Token do GitHub para autorização
